services:
  - type: web
    name: skillbridge
    env: node
    plan: free
    region: ohio
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
